#!/sbin/openrc-run
# Copyright 2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="dump1090 Flight Aware Daemon"
description=""
command=/usr/bin/dump1090
command_args="$RECEIVER_OPTIONS $DECODER_OPTIONS $NET_OPTIONS $JSON_OPTIONS $POSITION ${WISDOM_FILE:+--wisdom} ${WISDOM_FILE}"
command_user="dump1090:dump1090"
pidfile="/run/dump1090-fa.pid"
command_background=true

depend() {
  use rtl_tcp lighttpd
}
